### ISSUE TITLE
Logical switches are inverted

### ISSUE THREAD

**Issue by tomaskir** [offer-shmuely/edgetx-x10-widgets#11]
Hi, I am trying to use the flights widget with a logical switch as the "switch" to trigger a flight (it's the same logical switch I use for arming). However, in the widget, when using a logical switch, its inverted.

As in, when a logical switch is "low" (not triggered), in the widget the switch is ON. When the switch is high (triggered), in the widget the switch is OFF.

This means I can't use the flights widget together with arming on a logical switch. Any way I can do this?

**Comment by offer-shmuely** [comment]
the lua API of edgeTx (in openTx is the same) does NOT supply an option for the user to choose switch position,
that is sad, but that is the current options, I can only give the user an option to choose a switch, not up/middle/down
I can assure you, that in the moment that edgeTx dev's will give this option I will update the widget
so you are welcome to ask for it.
currently, your best option is to define a logical switch, with the setup that you like, and supply the logical switch to the widget, instead of the switch itself.

**Comment by tomaskir** [comment]
> the lua API of edgeTx (in openTx is the same) does supply an option for the user to choose switch position, that is sad, but that is the current options, I can only give the user an option to choose a switch, not up/middle/down I can assure you, that in the moment that edgeTx dev's will give this option I will update the widget so you are welcome to ask for it. currently, your best option is to define a logical switch, with the setup that you like, and supply the logical switch to the widget, instead of the switch itself.

@offer-shmuely I understand, however as mentioned in the original post, I am already using a logical switch for the "switch" setting, and that logical switch is not working for me.

**Comment by offer-shmuely** [comment]
Can you send me you model here?

**Comment by niraami** [comment]
Same here, I've got a pretty complex arming/disarming setup, so I have to use a logical switch to properly represent when my quad is armed, but it says "ON" when the logical switch is false, and "OFF" when it's true.
My guess is, that this logic [here](https://github.com/offer-shmuely/edgetx-x10-widgets/blob/master/WIDGETS/Flights/main.lua#L250) doesn't hold up to logical switches, as, I assume, false = 0 and true = 1, unlike the positions of physical switches?  But tbh i got no clue, been a while since I touched LUA, and I have never tried to make anything for EdgeTX.

Here's my model: [ELRS quad.txt](https://github.com/offer-shmuely/edgetx-x10-widgets/files/13863178/ELRS.quad.txt) (github doesn't allow .yml files, so it's a .txt)

**Comment by niraami** [comment]
Wait a second, I now tried setting it to a normal 2POS switch (SF).. and it's inverted too??
Are you aware that "up" is "off" and "down" is "on"? I'm now thinking the logic is inverted in general. Either way, an "invert logic" option in the widget settings would probably be nice.
![image](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/24532624/62b2627e-0fb0-462d-a257-5ad8395f7825)
As per the EdgeTX setup wiki: https://edgetx.gitbook.io/edgetx-user-manual/b-and-w-radios/model-select/setup

Edit: well damn, I guess adding an option isn't an *option* because of https://github.com/EdgeTX/edgetx/issues/1840
I guess I'll just modify the widget so that it works for my use case...

**Comment by offer-shmuely** [comment]
Hi
on our club, we use SF for arm switch 
SF up is off because it reduce the chance that the prop will turn on, if the TX will fall or bump with something 

and the script is adapt to this logic
I with i could have more setting,
Let me see what i can do…

**Comment by niraami** [comment]
No problem, I didn't think that edgetx widgets were this limited. Seems like they're planning to fix it, but I personally think just adding a JSON/YML configuration file onto the radio would make more sense, that's what I'd do If I wanted to make a widget now.

**Comment by offer-shmuely** [comment]
Hi
please the following enhancement (ver 0.9)

on the /flights/main.lua
under configuration  (line: 68)

I added inverted_switch_logic
0=armed when SF up
1=armed when SF down (my default)
