### ISSUE TITLE
Flight Widget Sounds

### ISSUE THREAD

**Issue by mhk1058** [offer-shmuely/edgetx-x10-widgets#18]
Hi,

Love the flights widget, thanks!

I watched John on RC Video Reviews talking about the flights widget and in his overview there was a sounds check box to choose whether the flights sounds were active or not... I don't seem to have this on Edge TX 2.10.2. Has these been removed? Quite handy to have.

**Comment by offer-shmuely** [comment]
yes, it was removed
not that it is not nice to have, but lua widgets are still limited to have 5 options
and I decided that the "inverted_arm_switch" is more important to be as an option.

since users that do not like the sound, usually don't like it generally, and not per model
while the "inverted_arm_switch" is per model

so you can edit the file on line 65
https://github.com/offer-shmuely/edgetx-x10-widgets/blob/master/WIDGETS/Flights/main.lua#L65

and change it to:
local enable_sounds = 0

**Comment by mhk1058** [comment]
Aha, that makes sense. I do use the inverted arm switch and now managed to change to my own sounds in the widgets/flights folder. Thanks for the work on these, really nice to have.
