### ISSUE TITLE
Different displays for "Value2" widget

### ISSUE THREAD

**Issue by OldAl-RC** [offer-shmuely/edgetx-x10-widgets#20]
The display for Value2 widgets differs depending on whether there is active telemetry or not. When there is telemetry the values are very small and unusable in normal operation, however when disabling the receiver (i.e. no telemetry) the display changes and things are much larger. See attached files for examples.

![NoTelemetry](https://github.com/user-attachments/assets/6ca0e5e0-ec81-4fd1-8232-87529a2711be)
![WithTelemetry](https://github.com/user-attachments/assets/2389079d-ccfb-4188-b190-8a7bb8b4a20c)

**Comment by OldAl-RC** [comment]
Oh, the labels are missing on the "With telemetry" because I had the text color set as black, so that is not an issue other than why they show up just fine in the "NoTelemetry" view. Also note that the two widgets for A1+ and A1- are normal "Value" widgets, not "Value2".

**Comment by offer-shmuely** [comment]
hi
welcome
first lets see that you are on the latest version
please update the widget from here: https://github.com/offer-shmuely/edgetx-x10-widgets/tree/master/WIDGETS/Value2

second, the font expected to change vs when the plane is arm or on flight, vs after landing for review
for example, RQly,
when armed and during all the flight, we expect the online value to be big, and min/max very small (depend on the size left)
after landing, when telemetry is disconnected, the is no online value (it's disconnected), so the past value of 100% is going to be useless, so it's font will be reduced (the 100% say nothing on this stage) and the min/max will be larger
since you do care on the minimum value of the RQly during all the flight (if it reduced of 80%, you need to start warried)
both the max (of 100%) and the last (frozen value of 100%) are useless.

**Comment by OldAl-RC** [comment]
Have made some changes, but still not quite there yet. First item was to clone the entire project so I could get the "official" code. looking for differences with my current card contents showed a lot of differences, so first item was to COMPLETELY update everything, including SD Card, to the latest .3 versions. Still a couple small differences despite both versions of lua scripts to claim to be version 0.8. Now the display when telemetry is present is perfect in my view, nice big clear values and labels. (One thing I notice is that the labels for Value2 stuff are missing the little telemetry indicator that is present on the basic Value labels for the voltage.)

![WithTelem](https://github.com/user-attachments/assets/27cfc426-dadb-4983-9d68-7ff041b21840)

However when disconnecting the receiver, and thus no more telemetry, the view is not nearly as good.

![NoTelem](https://github.com/user-attachments/assets/0bfb6bca-3564-46f5-8333-3fd22ca606ab)

As can be seen, the display for the basic "Value" widgets (right side, bottom 2, A+ and A-) are fine, the top 2 are terrible, and the left side lower 2 great but no labels.

**Comment by offer-shmuely** [comment]
What layout? 3+3?
Can you disable  sliders / trims / flight mode

**Comment by OldAl-RC** [comment]
Yes, it is 3+3. Can't disable trims, as they are all used for something, and I don't use flight mode. Do you want my YAML file?

**Comment by offer-shmuely** [comment]
Yes please
Send the the yaml, or the etx file

**Comment by OldAl-RC** [comment]
Sent via email.

**Comment by offer-shmuely** [comment]
did not get any mail
in the mean time, please test this version
[value2-0.9-test1.zip](https://github.com/user-attachments/files/16827544/value2-0.9-test1.zip)

**Comment by OldAl-RC** [comment]
OK, looks different but only partway there...

![WithTelem](https://github.com/user-attachments/assets/ab4e077a-7cf0-4089-8b4a-5fd7b174f29a)

Then without telemetry

![WithoutTelem](https://github.com/user-attachments/assets/0c3db0cc-1525-40d7-bba4-b5eecf240a5b)

I also have noticed that the value for A- in the "Without" screen looks very odd and does not match the comparable value in the "With" screen. This might be just the recording of a very low value as the power to the plane bleeds off after pulling the battery, but is still sufficient to send one last telemetry value. Just means to check the battery values while still connected, not a problem, just a procedural issue.

**Comment by OldAl-RC** [comment]
Here is the yml file for the model...I hope!

[model23.yml.zip](https://github.com/user-attachments/files/16829564/model23.yml.zip)

**Comment by offer-shmuely** [comment]
Looks ok to me.
What is still missing?

The A- that you show is not a value2 display (it is the C++ internal widget)

**Comment by OldAl-RC** [comment]
Nothing is actually missing. The only question is why is the font size so much bigger in the top 2 Value2 boxes (RSSI and RNse) as opposed to the other 2 Value2 boxes (RQly and RSNR)? Also the top boxes have **no** display for what I think is the current value, while the other 2 boxes have that value (whatever it is) just above the min..max display? I am not sure that in this context whatever that value is, it has no real meaning. Perhaps the absence of that value causes the font size to be set automatically based on available space? Looking at the YML file I see no differences at all other than the specification of a different telemetry parameter.

**Comment by offer-shmuely** [comment]
the calculation of font size is very hard since do not have enough font sizes


On  with-telemetry mode, I place the current value as big as possible, and if there is a space left, i put also the min/max values

On  no-telemetry mode, I place the min/max as big as possible, and if there is a space left, i put also the current value

it looks like the top ones have no units (the "db")
So it have less text, so it got a bigger font,
And no space left for current value.
I do hope the dev team will add more fonts

**Comment by OldAl-RC** [comment]
OK, I understand. Yes, more font sizes would likely be useful, but I can get along with it like this. Thanks for the support. I assume the changes you made will work their way into the future releases.

**Comment by OldAl-RC** [comment]
I guess I should have clicked "Close with comment".
